import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import '../App.css';

export default function TermsOfService() {
  return (
    <div className="legal-page">
      <Helmet>
        <title>Terms of Service | InfraSketch</title>
        <meta name="description" content="InfraSketch terms of service. Read our terms and conditions for using the agent-powered system design tool." />
        <link rel="canonical" href="https://infrasketch.net/terms" />
        <meta name="robots" content="noindex, follow" />
      </Helmet>

      <div className="legal-header">
        <Link to="/" className="legal-back-link">&larr; Back to InfraSketch</Link>
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: December 2, 2025</p>
      </div>

      <div className="legal-content">
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using InfraSketch ("the Service"), you agree to be bound
            by these Terms of Service. If you do not agree to these terms, please do
            not use the Service.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            InfraSketch is an agent-powered tool that helps users create system architecture
            diagrams. The Service uses artificial intelligence to generate diagrams based
            on user descriptions, allows interactive modification of designs, and generates
            technical documentation.
          </p>
        </section>

        <section>
          <h2>3. User Accounts</h2>
          <p>
            To use certain features of InfraSketch, you must create an account. You are
            responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activities that occur under your account</li>
            <li>Notifying us immediately of any unauthorized access</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2>4. Intellectual Property</h2>

          <h3>Your Content</h3>
          <p>
            You retain all rights to the diagrams, designs, and documentation you create
            using InfraSketch. We do not claim ownership of your content.
          </p>

          <h3>Our Service</h3>
          <p>
            The InfraSketch platform, including its design, code, and AI capabilities,
            is owned by InfraSketch. You may not copy, modify, or reverse engineer any
            part of the Service.
          </p>

          <h3>Agent-Generated Content</h3>
          <p>
            Diagrams and documentation generated by our agent are provided for your use.
            You are responsible for reviewing and validating agent-generated content before
            using it in production systems.
          </p>
        </section>

        <section>
          <h2>5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any illegal purpose</li>
            <li>Attempt to gain unauthorized access to our systems</li>
            <li>Interfere with or disrupt the Service</li>
            <li>Use automated tools to excessively access the Service</li>
            <li>Upload malicious content or code</li>
            <li>Impersonate others or provide false information</li>
            <li>Use the Service to generate harmful or offensive content</li>
          </ul>
        </section>

        <section>
          <h2>6. Service Availability</h2>
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted
            access to the Service. We may modify, suspend, or discontinue any part of
            the Service at any time without notice.
          </p>
          <p>
            <strong>Data Retention:</strong> Design sessions are automatically deleted
            after 24 hours of inactivity. Please export important designs before this
            period expires.
          </p>
        </section>

        <section>
          <h2>7. Limitation of Liability</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. TO THE
            MAXIMUM EXTENT PERMITTED BY LAW, INFRASKETCH SHALL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING
            BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR USE.
          </p>
          <p>
            You acknowledge that agent-generated content may contain errors or inaccuracies.
            InfraSketch is not responsible for any decisions made based on agent-generated
            diagrams or documentation.
          </p>
        </section>

        <section>
          <h2>8. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless InfraSketch from any claims, damages,
            or expenses arising from your use of the Service or violation of these terms.
          </p>
        </section>

        <section>
          <h2>9. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service at any time, with or
            without cause, with or without notice. Upon termination, your right to use
            the Service will immediately cease.
          </p>
          <p>
            You may terminate your account at any time by contacting us at{' '}
            <a href="mailto:contact@infrasketch.net">contact@infrasketch.net</a>.
          </p>
        </section>

        <section>
          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms of Service at any time. We will
            notify users of significant changes by posting the updated terms on this page.
            Your continued use of the Service after changes constitutes acceptance of the
            new terms.
          </p>
        </section>

        <section>
          <h2>11. Governing Law</h2>
          <p>
            These Terms of Service shall be governed by and construed in accordance with
            the laws of the United States, without regard to conflict of law principles.
          </p>
        </section>

        <section>
          <h2>12. Contact Us</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at:
          </p>
          <p>
            <a href="mailto:contact@infrasketch.net">contact@infrasketch.net</a>
          </p>
        </section>
      </div>
    </div>
  );
}
