"""Prompts for Infrastructure-as-Code generation.

One shared scaffold plus a per-target section. The scaffold carries the rules
that matter for trust (scaffold labeling, honest assumptions, no invented
credentials); the target section carries the resource vocabulary.
"""

# Prepended verbatim to every generated file by the generator, not by the model,
# so it cannot be forgotten or reworded.
FILE_HEADER = (
    "Generated by InfraSketch from an architecture diagram.\n"
    "This is a scaffold, not production-ready infrastructure. Review every "
    "resource, size it for your actual load, and supply your own networking, "
    "IAM, and secrets before applying."
)

TARGETS = {
    "terraform": {
        "label": "Terraform (AWS)",
        "extension": ".tf",
        "comment_prefix": "#",
        "guidance": """Target: **Terraform for AWS**.

Emit these files:
- `main.tf` - provider block, all resources
- `variables.tf` - every value someone must supply (region, environment, instance sizes, db credentials via variable, never literals)
- `outputs.tf` - endpoints and ARNs a caller would need
- `README.md` - what this creates, what it deliberately omits, and the exact commands to run

Default node-type to resource mapping (override it whenever
`metadata.technology` names something specific):
- `database` -> `aws_db_instance` (RDS). Postgres/MySQL/etc. from the technology field.
- `cache` -> `aws_elasticache_cluster` (Redis unless the technology says Memcached)
- `queue` -> `aws_sqs_queue`. If the technology says Kafka, use `aws_msk_cluster`.
- `cdn` -> `aws_cloudfront_distribution`
- `loadbalancer` / `gateway` -> `aws_lb` (application) plus target group and listener
- `storage` -> `aws_s3_bucket` plus a public-access block
- `api` / `server` / `service` -> `aws_ecs_service` on Fargate with a task definition
- anything else -> the closest AWS primitive, and note the choice in `assumptions`

Requirements:
- Pin the AWS provider version.
- Every resource gets tags including `ManagedBy = "InfraSketch"`.
- Use variables for anything environment-specific. Never hardcode account IDs,
  regions, AMIs, or passwords.
- Wire the diagram's edges into security groups: if A connects to B, A's
  security group should be allowed to reach B's port.
- Do not invent VPC/subnet infrastructure silently. Either create a minimal VPC
  explicitly, or take subnet IDs as variables. Say which you did in `assumptions`.
""",
    },
    "kubernetes": {
        "label": "Kubernetes manifests",
        "extension": ".yaml",
        "comment_prefix": "#",
        "guidance": """Target: **Kubernetes manifests**.

Emit one file per logical component, named after the component
(e.g. `api-server.yaml`), plus:
- `namespace.yaml`
- `README.md` - apply order and what must be supplied first

Default node-type mapping (override it whenever `metadata.technology` names
something specific):
- `api` / `server` / `service` -> Deployment + Service (ClusterIP)
- `database` -> StatefulSet + headless Service + PersistentVolumeClaim
- `cache` -> Deployment + Service (Redis unless stated otherwise)
- `queue` -> StatefulSet (Kafka/RabbitMQ) or a note that a managed queue is better
- `loadbalancer` / `gateway` -> Ingress
- `cdn` -> not a Kubernetes concept: omit it and say so in `warnings`
- `storage` -> PersistentVolumeClaim, or a note that object storage belongs outside the cluster

Requirements:
- Every Deployment/StatefulSet declares resource requests and limits, a readiness
  probe, and a liveness probe.
- Configuration goes in a ConfigMap; secrets go in a Secret with placeholder
  values clearly marked as placeholders.
- Use `apps/v1` and `networking.k8s.io/v1`. No deprecated API versions.
- Label everything consistently with `app.kubernetes.io/name` and
  `app.kubernetes.io/managed-by: infrasketch`.
""",
    },
    "compose": {
        "label": "Docker Compose",
        "extension": ".yaml",
        "comment_prefix": "#",
        "guidance": """Target: **Docker Compose**, for local development of this system.

Emit exactly:
- `compose.yaml`
- `.env.example` - every variable the compose file references
- `README.md` - how to bring it up and what is faked locally

Default node-type mapping (override it whenever `metadata.technology` names
something specific):
- `database` -> the official image for the named engine (`postgres:16`, `mysql:8`)
  with a named volume
- `cache` -> `redis:7-alpine`
- `queue` -> the official image for the named broker
- `api` / `server` / `service` -> a `build:` stanza pointing at a plausible
  service directory, since there is no image to pull
- `loadbalancer` / `gateway` -> `nginx:alpine` with a config note
- `cdn` -> omit; note in `warnings` that a CDN has no local equivalent
- `storage` -> `minio/minio` as an S3 stand-in

Requirements:
- Use the modern Compose spec (no top-level `version:` key).
- Named volumes for every stateful service, so data survives a restart.
- `depends_on` reflecting the diagram's edges, with `condition: service_healthy`
  wherever a healthcheck exists.
- A healthcheck on every service that has an obvious one.
- Every secret comes from `.env`, referenced as `${VAR}`. No literal passwords in
  `compose.yaml` beyond the `.env.example` defaults.
""",
    },
}

IAC_PROMPT = """You are a senior infrastructure engineer translating an architecture diagram into infrastructure code.

{diagram_context}

{target_guidance}

Rules:

1. **Only model what the diagram shows.** Do not add components that are not in
   the diagram because they would be good practice. If something important is
   missing (no monitoring, no VPC), list it in `warnings` instead of inventing it.
2. **Prefer the stated technology.** Each node may carry a
   `metadata.technology`. When it names something concrete (Postgres, Redis,
   Kafka, nginx), use that, and only fall back to the type-based default when it
   is absent or vague.
3. **Every assumption you make goes in `assumptions`.** Instance sizes, port
   numbers, replica counts, image tags, network layout: if the diagram did not
   say it and you chose it, say so. This list is shown to the user above the code.
4. **Never emit real or placeholder-looking credentials.** No access keys, no
   passwords, no account IDs. Use variables or clearly-marked placeholders like
   `CHANGE_ME`.
5. **The code must be syntactically valid** and pass the target's standard
   validator (`terraform validate`, `kubectl apply --dry-run=client`,
   `docker compose config`). This matters more than covering every node.
6. Use the node's `label` to derive readable resource names. Convert to the
   naming convention the target expects (snake_case for Terraform resource names,
   kebab-case for Kubernetes and Compose).

Call the `emit_iac_files` tool exactly once. Do not reply with prose or code
fences.
"""
